root: true

parser: '@babel/eslint-parser'

extends:
  - pegasus
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  class-methods-use-this: off # TODO: Remove after pegasus update to v3

overrides:
  - files:
      - 'tests/*.js'
    env:
      jest: true

settings:
  react:
    version: detect

env:
  browser: true
