root: true

extends:
  - pegasus
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off

overrides:
  - files:
      - 'tests/*.js'
    env:
      jest: true

settings:
  react:
    version: detect

env:
  browser: true
