root: true

parser: '@babel/eslint-parser'

extends:
  - pegasus
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off

overrides:
  - files:
      - 'scripts/*.js'
    extends:
      - pegasus/node
    rules:
      no-console: off

settings:
  react:
    version: detect

env:
  browser: true
